server:
  port: 3000

db:
  url: 'postgres://pvqypmmedqizey:60fee49ee1390f35da40d785c86eaf71d2788cd6abb39dcf9d2e199c90273399@ec2-54-211-77-238.compute-1.amazonaws.com:5432/d6rfrr68dd1c5c'
  synchronize: true
  ssl: {
    rejectUnauthorized: false,
  }

jwt:
  expiresIn: '10h' # 10 hours
  secret: 'cinema123'